version: '3.7'

services:

  sample:
    container_name: xplotur_b2c
    stdin_open: true
    tty: true
    image: smitpatel3110/xrox_front
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
      # - 443:3000
    environment:
      - CHOKIDAR_USEPOLLING=true