version: '3.7'

services:

  sample:
    container_name: xplotur_b2c
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "443:3000"
      # - 443:3000
    environment:
      - CHOKIDAR_USEPOLLING=true